#----------SERVER
server:
  port: 8081


#----------LOG
logging:
  config: file:/svc/apps/so/so/so-serviceprocessor/conf/logback-sp.xml

#----------PROCESSOR LIST
so:
  serviceprocessor:
    contextmodel.enable: true
    orchestrationservice.enable: true
    virtualobject.enable: true
    devicecontrol.enable: true

#----------DEVICE DRIVER
  device:
    driver.path: /svc/apps/so/so/driver

#----------MESSAGE QUEUE
mq:
  broker.list: localhost:9092
  zookeeper.list: localhost:2181

  ##---------PRODUCER: All values referenced from Kafka
  # ACKS_CONFIG
  producer:
    acks: 2
    # RETRIES_CONFIG
    retries: 0
    # BATCH_SIZE_CONFIG
    batch_size: 16384
    # LINGER_MS_CONFIG
    linger_ms: 1
    # BUFFER_MEMORY_CONFIG SIZE
    buffer_memoryproducer.buffer_memoryproducer.buffer_memory: 33554432

  ##---------CONSUMER: All values referenced from Kafka
  # POLL_TIMEOUT=3000L
  consumer:
    pool_timeout: 4000
    # ENABLE_AUTO_COMMIT_CONFIG=true
    enable_auto_commit: false
    # AUTO_COMMIT_INTERVAL_MS_CONFIG
    auto_commit_interval_ms: 1000
    # SESSION_TIMEOUT_MS_CONFIG
    session_timeout_ms: 15000
    # AUTO_OFFSET_RESET_CONFIG
    auto_offset_reset_config: earliest

#----------BANNER
banner:
  location: banner.txt
  charset: UTF-8

#----------DATABASE
spring:
  datasource:
    url: jdbc:mysql://rgate.synology.me:33306/serviceorchestration?useUnicode=true&characterEncoding=utf-8
    username: orchestrator
    password: pine123
    driverClassName: com.mysql.jdbc.Driver

  #spring.jpa.hibernate.ddl-auto=create-drop
#  jpa:
#    generate-ddl: false
#    database: mysql
#    show-sql: true

#----------MONGO DB
#  data:
#    mongodb:
#      database: so
#      host: 166.104.112.37
#      spring.data.mongodb.port: 37017
      #spring.data.mongodb.host=127.0.0.1
      #spring.data.mongodb.port=27017
#      repositories.enabled: true

#----------REMOTE SHELL
shell:
  auth:
    simple:
      user:
        name: so
        password: so!@#

kafka:
  topic:
    tracking: tracking
    contextmodel: contextmodel
    orchestrationservice: orchestrationservice
