/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'existmaster' at '16. 8. 3 오후 4:08' with Gradle 2.8
 *
 * @author existmaster, @date 16. 8. 3 오후 4:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
