#----------SERVER
server:
  port: 8080
  contextPath: /so

#----------LOG
logging:
  config: file:D:/svc/apps/so/so/so-web/conf/logback-web.xml

#----------PROCESSOR LIST
so:
  serviceprocessor:
    contextmodel.enable: true
    orchestrationservice.enable: true
    virtualobject.enable: true
    devicecontrol.enable: true
#----------Scheduler
  scheduler.enable: true
#----------DEVICE DRIVER
  device.driver.path: /svc/apps/so/so/driver

#----------MESSAGE QUEUE
mq:
  broker.list: localhost:9092
  zookeeper.list: localhost:2181

##---------PRODUCER: All values referenced from Kafka
# ACKS_CONFIG
  producer:
    acks: 2
# RETRIES_CONFIG
    retries: 0
# BATCH_SIZE_CONFIG
    batch_size: 16384
# LINGER_MS_CONFIG
    linger_ms: 1
# BUFFER_MEMORY_CONFIG SIZE
    buffer_memory: 33554432

##---------CONSUMER: All values referenced from Kafka
# POLL_TIMEOUT: 3000L
  consumer:
    pool_timeout: 4000
# ENABLE_AUTO_COMMIT_CONFIG: true
    enable_auto_commit: false
# AUTO_COMMIT_INTERVAL_MS_CONFIG
    auto_commit_interval_ms: 1000
# SESSION_TIMEOUT_MS_CONFIG
    session_timeout_ms: 15000
# AUTO_OFFSET_RESET_CONFIG
    auto_offset_reset: earliest

#----------BANNER
banner:
  location: banner.txt
  charset: UTF-8

#----------DATABASE
spring:
  datasource:
    url: jdbc:mysql://166.104.112.37:33306/so?useUnicode=true&characterEncoding=utf-8
    username: orchestrator
    password: pine123
    driverClassName: com.mysql.jdbc.Driver
#spring.jpa.hibernate.ddl-auto: create-drop
  #jpa:
  #  generate-ddl: false
  #  database: mysql
  #  show-sql: true
#----------MONGO DB
  #data:
  #  mongodb:
  #    database: so
  #    #host: 166.104.112.37
  #    #port: 37017
  #    host: 127.0.0.1
  #    port: 27017
  #    repositories.enabled: true

#----------REMOTE SHELL
#shell.auth.simple.user.name: so
#shell.auth.simple.user.password: so!@#

kafka:
  topic:
    tracking: tracking
    contextmodel: contextmodel
    orchestrationservice: orchestrationservice
