#----------server
server:
  port: 8080

#----------log
#logging.config=classpath:logback-${spring.profiles.active}.xml
logging:
  config: file:/svc/apps/so/so/so-id-db/conf/logback-if-db.xml
#logging.level.root=debug
  level:
    com.pineone.icbms.so: debug
#show sql statement
    org.hibernate.SQL: debug
#show sql values
    org.hibernate.type.descriptor.sql: trace

#----------banner
banner:
  locationForDB: banner.txt
  charset: UTF-8

#----------database
spring:
  datasource:
    #url: jdbc:mysql://rgate.synology.me:33306/serviceorchestration?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://166.104.112.37:33306/so?useUnicode=true&characterEncoding=utf-8
    username: orchestrator
    password: pine123
    driverClassName: com.mysql.jdbc.Driver
#  jackson:
#    mapper:
#      sort-properties-alphabetically: true

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.
#  jpa:
#    generate-ddl: false
#    database: mysql
#    show-sql: true

#----------remote shell
#shell.auth.simple.user.name=so
#shell.auth.simple.user.password=so!@#

#mybatis:
  #DatabaseConfig.java 에서 별도로 처리
  #mapper-locations: classpath:mappers/*.xml
  #type-aliases-package: com.pineone.icbms.so.interfaces.database.model
  #type-handlers-package: not defined
#  configuration:
#    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 30
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: false

primaryKey:
  prefix:
    orchestrationService: OS-
    virtaulObject: VO-
    compositeVirtualObject: CVO-
    profile: PR-
    contextModel: CM-
    contextInformation: CI-