#----------server
server:
  port: 8080

#----------log
#logging.config=classpath:logback-${spring.profiles.active}.xml
logging:
  config: file:./conf/logback-if-db.xml
#logging.level.root=debug
  level:
    com.pineone.icbms.so: debug
#show sql statement
    org.hibernate.SQL: debug
#show sql values
    org.hibernate.type.descriptor.sql: trace

#----------banner
banner:
  locationForDB: banner.txt
  charset: UTF-8

#----------database
spring:
  datasource:
    #url: jdbc:mysql://rgate.synology.me:33306/serviceorchestration?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://166.104.112.37:33306/so?useUnicode=true&characterEncoding=utf-8
    username: orchestrator
    password: pine123
    driverClassName: com.mysql.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.
  jpa:
    generate-ddl: false
    database: mysql
    show-sql: true

#----------remote shell
#shell.auth.simple.user.name=so
#shell.auth.simple.user.password=so!@#