package com.pineone.icbms.so.iot.resources.context;

import com.pineone.icbms.so.resources.context.DefaultContext;

/**
 * Context for IoT service.<BR/>
 * Created by uni4love on 2015. 11. 13..
 */
public class IotServiceContext extends DefaultContext
{
	/**
	 * action: ACTION_TARGET_LOCATION
	 */
	public static final String ACTION_TARGET_LOCATION = "ACTION_TARGET_LOCATION";

	/**
	 * action: ACTION_TARGET_STUDENT
	 */
	public static final String ACTION_TARGET_STUDENT = "ACTION_TARGET_STUDENT";

	/**
	 * action: ACTION_OPTIMAL_TEMP
	 */
	public static final String ACTION_OPTIMAL_TEMP = "ACTION_OPTIMAL_TEMP";

	/**
	 * action: ACTION_DEVICE_URI
	 */
	public static final String ACTION_DEVICE_URI = "ACTION_DEVICE_URI";

	/**
	 * action: ACTION_PHYSICAL_DEVICE_URI
	 */
	public static final String ACTION_PHYSICAL_DEVICE_URI = "ACTION_PHYSICAL_DEVICE_URI";

	/**
	 * action: ACTION_PHYSICAL_DEVICE_URI_ONE
	 */
	public static final String ACTION_PHYSICAL_DEVICE_URI_ONE = "ACTION_PHYSICAL_DEVICE_URI_ONE";

	/**
	 * action: ACTION_DEVICE_DRIVER
	 */
	public static final String ACTION_DEVICE_DRIVER = "ACTION_DEVICE_DRIVER";

	/**
	 * action: ACTION_PHYSICAL_DEVICE_DRIVER
	 */
	public static final String ACTION_PHYSICAL_DEVICE_DRIVER = "ACTION_PHYSICAL_DEVICE_DRIVER";

	/**
	 * action: ACTION_OPERATION_VALUE
	 */
	public static final String ACTION_OPERATION_VALUE = "ACTION_OPERATION_VALUE";

	/**
	 * action: ACTION_PHYSICAL_OPERATION_VALUE
	 */
	public static final String ACTION_PHYSICAL_OPERATION_VALUE = "ACTION_PHYSICAL_OPERATION_VALUE";

	/**
	 * action: ACTION_STUDENT_MANAGER
	 */
	public static final String ACTION_STUDENT_MANAGER = "ACTION_STUDENT_MANAGER";

	/**
	 * action: ACTION_STUDENT_DETAIL
	 */
	public static final String ACTION_STUDENT_DETAIL = "ACTION_STUDENT_DETAIL";

	/**
	 * action: ACTION_ONTOLOGY_REFERENCE
	 */
	public static final String ACTION_ONTOLOGY_REFERENCE = "ACTION_ONTOLOGY_REFERENCE";

	/**
	 * action: ACTION_PHYSICAL_ONTOLOGY_REFERENCE
	 */
	public static final String ACTION_PHYSICAL_ONTOLOGY_REFERENCE = "ACTION_PHYSICAL_ONTOLOGY_REFERENCE";

	/**
	 * action: ACTION_EMERGENCYNOTI_ZONE
	 */
	public static final String ACTION_EMERGENCYNOTI_ZONE = "ACTION_EMERGENCYNOTI_ZONE";

	/**
	 * action: ACTION_PHYSICAL_EMERGENCYNOTI_ZONE
	 */
	public static final String ACTION_PHYSICAL_EMERGENCYNOTI_ZONE = "ACTION_PHYSICAL_EMERGENCYNOTI_ZONE";

	/**
	 * action: ACTION_EMERGENCYNOTI_KIND
	 */
	public static final String ACTION_EMERGENCYNOTI_KIND = "ACTION_EMERGENCYNOTI_KIND";

	/**
	 * action: ACTION_PHYSICAL_EMERGENCYNOTI_KIND
	 */
	public static final String ACTION_PHYSICAL_EMERGENCYNOTI_KIND = "ACTION_PHYSICAL_EMERGENCYNOTI_KIND";

	/**
	 * action: ACTION_USERID
	 */
	public static String ACTION_USERID = "ACTION_USERID";

	/**
	 * action: ACTION_PHYSICAL_USERID
	 */
	public static String ACTION_PHYSICAL_USERID = "ACTION_PHYSICAL_USERID";

	/**
	 * action: ACTION_EMERGENCYNOTI_CAMURL
	 */
	public static String ACTION_EMERGENCYNOTI_CAMURL = "ACTION_EMERGENCYNOTI_CAMURL";

	/**
	 * action: ACTION_PHYSICAL_EMERGENCYNOTI_CAMURL
	 */
	public static String ACTION_PHYSICAL_EMERGENCYNOTI_CAMURL = "ACTION_PHYSICAL_EMERGENCYNOTI_CAMURL";

	/**
	 * action: ACTION_ALARMINFO_ALARMID
	 */
	public static String ACTION_ALARMINFO_ALARMID = "ACTION_ALARMINFO_ALARMID";

	/**
	 * action: ACTION_PHYSICAL_ALARMINFO_ALARMID
	 */
	public static String ACTION_PHYSICAL_ALARMINFO_ALARMID = "ACTION_PHYSICAL_ALARMINFO_ALARMID";

	/**
	 * action: ACTION_ALARMINFO_WAKETIME
	 */
	public static String ACTION_ALARMINFO_WAKETIME = "ACTION_ALARMINFO_WAKETIME";

	/**
	 * action: ACTION_PHYSICAL_ALARMINFO_WAKETIME
	 */
	public static String ACTION_PHYSICAL_ALARMINFO_WAKETIME = "ACTION_PHYSICAL_ALARMINFO_WAKETIME";

	/**
	 * action: ACTION_ALARMINFO_PERIOD
	 */
	public static String ACTION_ALARMINFO_PERIOD = "ACTION_ALARMINFO_PERIOD";

	/**
	 * action: ACTION_PHYSICAL_ALARMINFO_PERIOD
	 */
	public static String ACTION_PHYSICAL_ALARMINFO_PERIOD = "ACTION_PHYSICAL_ALARMINFO_PERIOD";

	/**
	 * action: ACTION_ALARMINFO_TYPE
	 */
	public static String ACTION_ALARMINFO_TYPE = "ACTION_ALARMINFO_TYPE";

	/**
	 * action:ACTION_PHYSICAL_ALARMINFO_TYPE
	 */
	public static String ACTION_PHYSICAL_ALARMINFO_TYPE = "ACTION_PHYSICAL_ALARMINFO_TYPE";

}
